name: 'Build and tag'

on:
  push:
    branches:
      - main 
    tags:
      - "!*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install

      - name: Run lint 
        run: |
          npm run lint --if-present

      - name: Run test 
        run: |
          npm run test:lib --if-present

      - name: Run build
        run: |
          npm run compile 
        env:
          NODE_ENV: production

      - name: get version 
        uses: bbonkr/get-version-action@v1.0.5
        id: get_version
        with:
         project: package.json

      - name: check tag exists
        uses: bbonkr/git-tag-check-action@v1.0.12
        id: check_tag
        with:
          tag: "v${{ steps.get_version.outputs.version }}"
          github_token: ${{ secrets.GH_TOKEN }}

      - name: package-version-to-git-tag
        uses: pkgdeps/git-tag-action@v2
        if: ${{ steps.check_tag.outputs.tag == '' }}
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.get_version.outputs.version }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: git tag skipped
        if: ${{ steps.check_tag.outputs.tag != '' }}
        run: |
          echo "Tag (v${{ steps.check_tag.outputs.tag }}) is exists already." 
        