name: "Verify PR"

on:
  pull_request:

jobs:
  verify-build:
    name: Verify to build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          npm install
      
      - name: lint 
        run: |
          npm run lint --if-present

      # It Needs X server or $DISPLAY
      # - name: test
      #   run: |
      #     npm run test --if-present

      - name: test lib
        run: |
          npm run test:lib --if-present

      - name: build
        run: |
          npm run compile 
        env:
          NODE_ENV: production

      - name: vscode:prepack
        run: |
          npm run vscode:prepublish
        env:
          NODE_ENV: production

      - name: Add comment 
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OUTPUT: "✅ This pull request is verified to build."
        with:
          msg: ${{ env.OUTPUT }}
          check_for_duplicate_msg: false